# Generated by Django 4.2.11 on 2025-09-09 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('mg', 'Milligrams'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('mm', 'Millimeters'), ('cm', 'Centimeters'), ('m', 'Meters'), ('km', 'Kilometers'), ('pcs', 'Pieces'), ('dozen', 'Dozen'), ('nos', 'nos')], max_length=10)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('pay_type', models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], max_length=50)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('bills', 'Bills & Utilities'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
            ],
        ),
    ]
